---
hero_image: images / robo-trumps.png
theme: бірюза
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Роботи-Козирки
description: Створіть базу даних роботів і грайте в Robo-Trumps з другом!
original_url: https://codeclubprojects.org/en-GB/python/robo-trumps
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Вступ
  - 
    title: Читайте дані робота з файлу
  - 
    title: Відображення даних
  - 
    title: 'Виклик: додайте більше роботів'
  - 
    title: 'Виклик: додайте більше статистичних даних роботам'
  - 
    title: Відображати випадковий робот
  - 
    title: 'Виклик: грайте в робот козир з другом'
