---
hero_image: प्रतिमा / robo-trumps.png
theme: नीलमणी
duration: 0
listed: true
ingredient: false
copyedit: false
curriculum: १, डिझाइन-0, प्रोग्रामिंग-१, भौतिक संगणन-0, उत्पादन-0, समुदाय-0
title: रोबो-ट्रम्प
description: रोबोटचा डेटाबेस तयार करा आणि मित्रासह रोबो-ट्रंप खेळा!
original_url: https://codeclubprojects.org/en-GB/python/robo-trumps
interests: खेळ
technologies: पायथन
site_areas: प्रकल्प
hardware: ''
software: पायथन
version: 0
last_tested: २०१७-०१-०१
steps:
  - 
    title: परिचय
  - 
    title: फाईलमधून रोबोट डेटा वाचा
  - 
    title: डेटा प्रदर्शित करा
  - 
    title: 'आव्हान: आणखी रोबोट जोडा'
  - 
    title: 'आव्हान: रोबोटमध्ये अधिक आकडेवारी जोडा'
  - 
    title: विनाक्रमित रोबोट प्रदर्शित करा
  - 
    title: 'आव्हान: मित्रासह रोबोट ट्रम्प खेळा'
