---
hero_image: imagens / robo-trumps.png
theme: turquesa
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Robo-Trumps
description: Crie um banco de dados de robôs e jogue Robo-Trumps com um amigo!
original_url: https://codeclubprojects.org/en-GB/python/robo-trumps
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Ler dados do robô de um arquivo
  - 
    title: Exibir os dados
  - 
    title: 'Desafio: adicione mais robôs'
  - 
    title: 'Desafio: adicione mais estatísticas aos robôs'
  - 
    title: Exibir um robô aleatório
  - 
    title: 'Desafio: Jogue com o robô em um amigo'
