---
hero_image: images/robo-trumps.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Borbe robota
description: U ovom projektu učitavat ćeš podatke iz datoteke i kreirati karte za igru robotima.
original_url: https://codeclubprojects.org/en-GB/python/robo-trumps
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - title: Uvod
  - title: Učitaj podatke o robotu iz datoteke
  - title: Prikaži podatke
  - title: 'Izazov: Dodaj još robota'
  - title: 'Izazov: Dodaj još karakteristika robotima'
  - title: Prikaži nasumičnog robota
  - title: 'Izazov: Zaigraj Borbe robota s prijateljem'
