---
hero_image: images/robo-trumps.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Cartas Robóticas
description: Crea una base de datos de robots, ¡y juega a Cartas Robóticas con un
  amigo!
original_url: https://codeclubprojects.org/en-GB/python/robo-trumps
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introducción
  completion: engaged
- title: Lee los datos del robot de un archivo
- title: Visualiza los datos
- title: 'Desafío: Añadir más robots'
- title: 'Desafío: Añadir más estadísticas a los robots'
- title: Visualiza un robot aleatorio
  completion: internal
- title: 'Desafío: Juega a Cartas robóticas con un amigo'
