hero_image: images/robo-trumps.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Robo-Trumps
description: Erstelle eine Datenbank mit Robotern und spiele Robo-Trumps mit einem Freund/einer Freundin!
original_url: https://codeclubprojects.org/en-GB/python/robo-trumps
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Einführung
- title: Lies die Roboter Daten aus einer Datei ab
- title: Daten anzeigen
- title: 'Aufgabe: Füge noch mehr Roboter hinzu'
- title: 'Aufgabe: Füge den Robotern weitere Statistiken hinzu'
- title: Einen beliebigen Roboter darstellen
- title: 'Aufgabe: Spiele Robot-Trumps mit einem Freund/einer Freundin'