---
hero_image: images/robo-trumps.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1，design-0，programming-1，phys-comp-0，manufacture-0，community-0
title: Robo-Trumps
description: 創建機器人數據庫並與朋友一起玩Robo-Trumps！
original_url: https://codeclubprojects.org/en-GB/python/robo-trumps
interests: games
technologies: python
site_areas: 專案
hardware: ''
software: python
version: 3
last_tested: 2017年1月1日
steps:
  - 
    title: 介紹
  - 
    title: 從文件中讀取機器人數據
  - 
    title: 顯示資料
  - 
    title: '挑戰：添加更多機器人'
  - 
    title: '挑戰：為機器人添加更多統計數據'
  - 
    title: 顯示隨機機器人
  - 
    title: 'Challenge: Play robot trumps with a friend'
