---
hero_image: images/robo-trumps.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Cartas Robóticas
description: Crea una base de datos de robots, ¡y juega Robo-Trumps con un amigo!
original_url: https://codeclubprojects.org/en-GB/python/robo-trumps
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - title: Introducción
  - title: Lee los datos del robot desde un archivo
  - title: Mostrar los datos
  - title: 'Desafío: Añadir más robots'
  - title: 'Desafío: Añadir más estadísticas a los robots'
  - title: Mostrar un robot aleatorio
  - title: 'Desafío: Juega "Cartas robóticas" con un amigo'
