---
hero_image: images/robo-trumps.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Robo-Atout
description: Créer une base de données et jouer à Robo-Atout avec un ami !
original_url: https://codeclubprojects.org/fr-FR/python/robo-trumps/
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Lire les données des robots à partir d'un fichier
  - 
    title: Afficher les données
  - 
    title: 'Défi : Ajoute d''autres robots'
  - 
    title: 'Défi : Ajoute plus de stats aux robots'
  - 
    title: Afficher un robot de façon aléatoire
  - 
    title: 'Défi : Joue à Robot-Atout avec un ami'
