---
hero_image: images/robo-trumps.png
theme: turkuaz
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-0, programlama-1, fiziksel-hesaplama-0, üretim-0, topluluk-0
title: Robo-Kozlar
description: Bir robot veritabanı oluşturun ve bir arkadaşınızla Robo-Kozlar oynayın!
original_url: https://codeclubprojects.org/en-GB/python/robo-trumps
interests: oyunlar
technologies: python
site_areas: projeler
hardware: ''
software: python
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Giriş
  - 
    title: Robot verilerini bir dosyadan oku
  - 
    title: Verileri görüntüle
    completion:
      - engaged
  - 
    title: 'Meydan Okuma: Daha fazla robot ekle'
  - 
    title: 'Meydan Okuma: Robotlara daha fazla istatistik ekle'
  - 
    title: Rastgele bir robotu görüntüle
    completion:
      - internal
  - 
    title: 'Meydan Okuma: Bir arkadaşınla robot kozlar oyna'
